// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  contact: dynamic(() => import("./Contact")),
  ctacomponent: dynamic(() => import("./Ctacomponent")),
  hero: dynamic(() => import("./Hero")),
  servicios: dynamic(() => import("./Servicios")),
};
